import { DEPTS, DEPT_KEYS, AGENTS, WORKLINES } from './data.js';

const app = document.querySelector('#app');
const toast = document.querySelector('#toast');
const logo = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/248338-removebg-preview-qhQpzYZIUxqk3xXKMrF0Sc2Rd3jrkq.png';
const colors = Object.fromEntries(DEPT_KEYS.map((key) => [key, DEPTS[key].chip]));
const byDept = (dept) => AGENTS.filter((agent) => agent.dept === dept);
const initials = (name) => name.split(' ').map((part) => part[0]).slice(0, 2).join('');
let view = 'landing';
let selectedDept = 'all';
let accent = '#d7b77a';
let compactMode = false;
let tasks = [
  { title: 'Review the September client report pack', agent: 'crep', state: 'IN PROGRESS', dept: 'delivery' },
  { title: 'Enrich overnight signups and route the batch', agent: 'enzo', state: 'RUNNING', dept: 'sales' },
  { title: 'Approve October content plan', agent: 'mlead', state: 'WAITING APPROVAL', dept: 'marketing' },
  { title: 'Reconcile unmatched card fees', agent: 'recon', state: 'QUEUED', dept: 'fin' },
];
function agent(id) { return AGENTS.find((item) => item.id === id) || AGENTS[0]; }
function showToast(message) { toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2200); }
function header() { return `<header class="topbar"><div class="brand-lockup"><img src="${logo}" alt="Ember Spark Crew emblem" /><div class="brand">DELUX CREW <small>BY EMBER SPARK</small></div></div><nav class="nav" aria-label="Primary navigation"><button class="${view === 'landing' ? 'active' : ''}" data-view="landing">The experience</button><button class="${view === 'office' ? 'active' : ''}" data-view="office">Connections</button><button class="${view === 'settings' ? 'active' : ''}" data-view="settings">Settings</button></nav><div class="spacer"></div><div class="status"><i></i> CONNECTED TO EMBER SPARK</div><button class="profile" aria-label="Open profile">DC</button></header>`; }
function landing() { return `${header()}<section class="landing"><div class="landing-grid"><div><div class="eyebrow">Your work, beautifully in order</div><h1>Big ideas.<br>Clear direction.<br><em>Your own space.</em></h1><p class="landing-copy">Bring your workflows, connections, and next steps together. Delux Crew gives your ambition a workspace that feels entirely yours.</p><div class="cta-row"><button class="primary" data-view="office">Create your workspace ↗</button><button class="ghost" data-view="office">Discover the experience</button></div><div class="fine">Personal workspace · No card required · Your own space</div></div><div class="workspace-card"><div class="workspace-label"><span>DELUX CREW / WORKSPACE</span><span>•••</span></div><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_20261008_121259_092-qR5IzfzvZnJgbxJSTLZspQeChBEDba.jpg" alt="Delux Crew workspace overview" /></div></div><div class="landing-strip"><div class="strip-title">YOUR CONNECTIONS<br>A WORLD OF POSSIBILITY.</div><span>◉ OpenAI</span><span>◉ WhatsApp</span><span>◉ Workspace</span><span>◉ 3D office</span></div><div class="feature-grid"><article class="feature"><b>01 / YOUR WORK</b><h3>See the whole picture.</h3><p>Every deliverable, approval, and next move in a single calm view.</p></article><article class="feature"><b>02 / YOUR CONNECTIONS</b><h3>Bring your tools closer.</h3><p>Connect the places your crew already works and keep context moving.</p></article><article class="feature"><b>03 / YOUR STYLE</b><h3>Make yourself at home.</h3><p>Shape your office with themes, density, and presence that feel like yours.</p></article></div></section>`; }
function queue() { return tasks.filter((task) => selectedDept === 'all' || task.dept === selectedDept).map((task) => { const owner = agent(task.agent); return `<div class="queue-item"><div class="queue-title">${task.title}</div><div class="queue-meta"><span>${owner.name}</span><span class="pill">${task.state}</span></div></div>`; }).join('') || '<div class="queue-item"><div class="queue-title">No work in this view.</div></div>'; }
function office() { const activeAgents = selectedDept === 'all' ? AGENTS : byDept(selectedDept); return `${header()}<section class="office-view"><div class="view-heading"><div><div class="eyebrow">Ember Spark Crew / live workspace</div><h1>3D office</h1><p>Dispatch work, see every department, and keep the next decision close.</p></div><button class="primary" id="newTask">+ New task</button></div><section class="layout"><div class="panel"><div class="panel-head"><h2>Office floor</h2><span>${selectedDept === 'all' ? 'Overview' : DEPTS[selectedDept].name}</span></div><div class="office">${DEPT_KEYS.map((key) => { const list = byDept(key); return `<button class="department ${selectedDept === key ? 'active' : ''}" style="--accent:${colors[key]}" data-dept="${key}"><div class="dept-top"><span class="dept-dot"></span><span class="dept-name">${DEPTS[key].name}</span></div><div class="dept-count">${list.length}</div><div class="dept-meta">agents assigned</div><div class="dept-foot"><span>${list.filter((a) => a.lead).length} lead</span><span>${WORKLINES[key]?.[0]?.replace('▸ ', '') || 'Standing by'}</span></div></button>`; }).join('')}</div><div class="panel-head"><h2>Live activity</h2><span>Updated just now</span></div><div class="feed">${activeAgents.slice(0, 5).map((a, index) => `<div class="feed-item"><span class="feed-mark">0${index + 1}</span><div class="feed-copy">${WORKLINES[a.dept]?.[index % (WORKLINES[a.dept]?.length || 1)] || 'Agent is ready for work'}<small>${a.name} · ${DEPTS[a.dept].name}</small></div></div>`).join('')}</div><div class="taskbar"><input id="taskInput" aria-label="Describe a task" placeholder="Tell the office what needs doing…" /><button class="primary" id="dispatch">Dispatch task</button></div></div><aside class="panel"><div class="panel-head"><h2>Work queue</h2><span>${tasks.length} items</span></div><div class="queue">${queue()}</div><div class="panel-head"><h2>Office pulse</h2><span>Today</span></div><div class="metrics"><div class="metric"><strong>47</strong><span>leads enriched</span></div><div class="metric"><strong>23</strong><span>invoices issued</span></div><div class="metric"><strong>9.5h</strong><span>call hours routed</span></div><div class="metric"><strong>6</strong><span>proposals sent</span></div><div class="metric"><strong>31</strong><span>tickets resolved</span></div><div class="metric"><strong>3</strong><span>need approval</span></div></div><div class="panel-head"><h2>On call now</h2><span>${activeAgents.length} shown</span></div><div class="agent-list">${activeAgents.slice(0, 7).map((a) => `<div class="agent"><div class="avatar" style="background:${colors[a.dept]}">${initials(a.name)}</div><div><div class="agent-name">${a.name}</div><div class="agent-role">${a.lead ? 'Department lead' : DEPTS[a.dept].name}</div></div><span class="agent-state">${a.id === 'mlead' ? 'review' : 'working'}</span></div>`).join('')}</div></aside></section></section>`; }
function settings() { return `${header()}<section class="settings"><div class="eyebrow">Delux Crew / workspace controls</div><h1>Make the office yours.</h1><p class="settings-intro">Configure the atmosphere and information density of your 3D office. Changes apply instantly to this workspace.</p><div class="settings-section"><div><h2>Platform theme</h2><p>Choose the accent that carries across your crew’s command centre.</p></div><div class="swatches"><button class="swatch ${accent === '#d7b77a' ? 'active' : ''}" style="background:#d7b77a" aria-label="Brass theme" data-accent="#d7b77a"></button><button class="swatch ${accent === '#84b9ad' ? 'active' : ''}" style="background:#84b9ad" aria-label="Teal theme" data-accent="#84b9ad"></button><button class="swatch ${accent === '#c18c75' ? 'active' : ''}" style="background:#c18c75" aria-label="Copper theme" data-accent="#c18c75"></button></div></div><div class="settings-section"><div><h2>Office display</h2><p>Keep the floor focused when you are moving quickly through work.</p></div><div><div class="setting-row"><div><strong>Compact activity feed</strong><small>Reduce the spacing between live updates.</small></div><button class="toggle ${compactMode ? 'on' : ''}" aria-label="Toggle compact activity feed" id="compactToggle"><i></i></button></div><div class="setting-row"><div><strong>Presence indicators</strong><small>Show which agents are working, waiting, or reviewing.</small></div><button class="toggle on" aria-label="Presence indicators enabled"><i></i></button></div></div></div><div class="settings-section"><div><h2>Brand</h2><p>Your workspace is part of the Ember Spark Crew network.</p></div><div class="setting-row"><div><strong>Delux Crew</strong><small>Powered by Ember Spark · workspace identity</small></div><span class="pill">ACTIVE</span></div></div></section>`; }
function render() { app.innerHTML = view === 'landing' ? landing() : view === 'office' ? office() : settings(); bind(); }
function dispatch() { const input = document.querySelector('#taskInput'); const title = input?.value.trim(); if (!title) { input?.focus(); return; } const owner = selectedDept === 'all' ? AGENTS.find((a) => a.lead) : byDept(selectedDept).find((a) => a.lead) || byDept(selectedDept)[0]; tasks = [{ title, agent: owner.id, state: 'QUEUED', dept: owner.dept }, ...tasks]; selectedDept = owner.dept; showToast(`Task routed to ${owner.name}`); render(); }
function bind() { document.querySelectorAll('[data-view]').forEach((button) => button.addEventListener('click', () => { view = button.dataset.view; render(); })); document.querySelectorAll('[data-dept]').forEach((button) => button.addEventListener('click', () => { selectedDept = selectedDept === button.dataset.dept ? 'all' : button.dataset.dept; render(); })); document.querySelectorAll('[data-accent]').forEach((button) => button.addEventListener('click', () => { accent = button.dataset.accent; document.documentElement.style.setProperty('--gold', accent); document.documentElement.style.setProperty('--gold-strong', accent); render(); })); document.querySelector('#compactToggle')?.addEventListener('click', () => { compactMode = !compactMode; document.body.dataset.compact = compactMode; render(); }); document.querySelector('#newTask')?.addEventListener('click', () => document.querySelector('#taskInput')?.focus()); document.querySelector('#dispatch')?.addEventListener('click', dispatch); document.querySelector('#taskInput')?.addEventListener('keydown', (event) => { if (event.key === 'Enter' && !event.nativeEvent?.isComposing && event.keyCode !== 229) dispatch(); }); }
render();
